### ISSUE TITLE
邮箱登录时一直提示 Network Error

### ISSUE THREAD

**Issue by BlueHtml** [aircodelabs/aircode#116]
使用**邮箱**登录时一直提示`Network Error`。360极速浏览器X 和 edge 的报错信息不一样。

360极速浏览器X 报错`net::ERR_SSL_PROTOCOL_ERROR`，如下图：

![image](https://github.com/AirCodeLabs/aircode/assets/17940898/b5fbb134-3e57-41a9-bab4-1370e82df3dd)

edge 报错`net::ERR_CONNECTION_CLOSED`，如下图：

![image](https://github.com/AirCodeLabs/aircode/assets/17940898/59256cae-91a9-4abe-9007-45609d25cd03)

**Comment by 0xinhua** [comment]
@BlueHtml 你好，我们在 3 月初发送了公告及邮件，AirCode 正式停止维护。
