### ISSUE TITLE
No Support local init

### ISSUE THREAD

**Issue by bestony** [aircodelabs/aircode#26]
I want to write some test for my project, but I can't init air code from local
<img width="756" alt="image" src="https://user-images.githubusercontent.com/13283837/219954918-45b3efc6-2017-4dae-a82a-29e21ed3afe3.png">

**Comment by adcentury** [comment]
Hi, @bestony. The `aircode` SDK can only be loaded inside the cloud function. You can create a new cloud function if you want to write some test code.
BTW, we will optimize the error message to provide better feedback for users.
