### ISSUE TITLE
部署后的接口域名不支持自定义

### ISSUE THREAD

**Issue by cduyzh** [AirCodeLabs/aircode#51]
eg:
 const domain = "https://w7umjdfjvc.hk.aircode.run"
 request url :  `${domain}/xxxxx`
希望domain这块支持自定义域名能解析到自己的上去

**Comment by adcentury** [comment]
你好，感谢反馈，这个功能在我们的规划中。

**Comment by adcentury** [comment]
Of course, you can start a new discussion in the [Feature Requests](https://github.com/orgs/AirCodeLabs/discussions/categories/feature-requests) category. We will consider updating the priority if people vote on the request.

**Comment by cduyzh** [comment]
好的
