### ISSUE TITLE
编辑器智能提示与体验问题

### ISSUE THREAD

**Issue by lemonAddInk** [AirCodeLabs/aircode#72]
1. ts 体验问题
<img width="520" alt="image" src="https://github.com/AirCodeLabs/aircode/assets/59479571/ae4717f1-800b-4b6d-a552-6cfc6e929942">

例如上面这样，我想输入个 interface ，但是编辑器都没智能提示。对 ts 的语法支持不太友好，还有个：想输入一个 string，也没智能提示，提示的是 String。

<img width="637" alt="image" src="https://github.com/AirCodeLabs/aircode/assets/59479571/83dde7f8-cfb4-4c4c-aa86-7f2880609411">

还有一个就是 params 已经定义好了类型，但是我输入 params. 的时候，编辑器不会自动给我提示 params 中有哪些属性，还要我自己输入个 n ，才能找到里面有个 name 属性。就感觉 ts 的功能大打折扣了

2. 文件过多杂乱
<img width="1005" alt="image" src="https://github.com/AirCodeLabs/aircode/assets/59479571/bf88e282-a93e-4bd3-9199-a9b8cc210e0e">
当 js 文件过多的时候，看起来整个目录会很多，是否考虑加个 文件夹功能 呢？

你们的产品做的不错，用的很爽，就是还有些细节问题哈哈哈，继续加油！

**Comment by 0xinhua** [comment]
@lemonAddInk Hi，谢谢你的反馈，编辑器智能提示和支持文件夹功能近期会上线。
