### ISSUE TITLE
文件夹与文件拖动位置异常

### ISSUE THREAD

**Issue by Ink-o** [AirCodeLabs/aircode#73]
Hi，我在使用你们的新功能的时候遇到了点问题

<img width="257" alt="image" src="https://github.com/AirCodeLabs/aircode/assets/59479571/5a39c821-f428-4ad1-987f-105b80be0829">

我尝试将 hello.ts 移动到指定 hello 文件夹内部，发现并没有任何反应，这应该是个bug？

<img width="262" alt="image" src="https://github.com/AirCodeLabs/aircode/assets/59479571/42b3ded2-936e-4241-9a27-47d157396b8c">

最外层的添加文件夹，不应该是直接在根部添加文件夹的？
每次我想在根部添加一个文件夹我还得点击一下根部的文件，才能在根部添加文件夹呢，这很麻烦。当我根部全部是文件夹的时候，我将无法在根部添加一个文件/文件夹，刷新也没办法

**Comment by 0xinhua** [comment]
@Ink-o Hi, 谢谢你的反馈以及对 AirCode 的支持，文件夹及文件目前还不支持拖拽移动; 当根目录都是文件夹时无法在根目录创建一个文件或文件夹，这部分我们已经优化：可点击文件区空白处取消选中效果，通过右上方的创建按钮会在根目录创建文件夹/文件

**Comment by Ink-o** [comment]
> @Ink-o Hi, 谢谢你的反馈以及对 AirCode 的支持，文件夹及文件目前还不支持拖拽移动; 当根目录都是文件夹时无法在根目录创建一个文件或文件夹，这部分我们已经优化：可点击文件区空白处取消选中效果，通过右上方的创建按钮会在根目录创建文件夹/文件

希望能支持下文件夹及文件移动的功能Thanks♪(･ω･)ﾉ，不然以前没有分类的代码只能手工cv过去，挺耗时的
