### ISSUE TITLE
支持本地开发

### ISSUE THREAD

**Issue by ModyQyW** [AirCodeLabs/aircode#85]
你们好！首先非常感谢你们的工作，AirCode 真的很棒！👍

目前文档会推荐使用 WebIDE 的方式开发，但个人更习惯使用 VS Code 开发。希望能支持本地开发、调试，可以通过 CLI 上传、部署 🙏

**Comment by akira-cn** [comment]
@ModyQyW 你可以试试 https://github.com/AirCodeLabs/Hydrogen，就可以支持本地开发，现在暂时不支持 CLI 上传，但是可以通过 GitHub 上传，具体你看文档： https://github.com/AirCodeLabs/Hydrogen/blob/main/docs/integration-with-aircode.md
