### ISSUE TITLE
upload image by postman error

### ISSUE THREAD

**Issue by phungvansyhb** [AirCodeLabs/aircode#93]
- my copy code :  

```
import aircode from 'aircode';
export default async function (params: any, context: any) {
  const { myFile } = params;
  const file = await aircode.files.upload(
    myFile.buffer, // Content of the file
    myFile.name // Name of the file
  );

  // return the URL of file
  return {
    url: file.url,
  };
}
```

then send post request in postman with body type form-data with key myFile , value is file which i pick. Then server show error: 

`Unexpected token - in JSON at position 0`

**Comment by akira-cn** [comment]
@phungvansyhb Hi~ This is a bug and I just fixed it. Could you try again pls.

**Comment by phungvansyhb** [comment]
yay, it works
